export const FETCH_PERFOMER_ERROR = 'PERFOMER/FETCH_PERFOMER_ERROR';
export const FETCH_PERFOMER_REQUEST = 'PERFOMER/FETCH_PERFOMER_REQUEST';
export const FETCH_PERFOMER_RESPONSE = 'PERFOMER/FETCH_PERFOMER_RESPONSE';